config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :servers, only: [:index, :destroy], param: :id do
        resources :interfaces, only: [:index, :destroy], param: :id, controller: 'servers/bandwidths'
      end
    end
  end

  resources :servers, only: [:index], param: :id do
    resources :interfaces, only: [:index], controller: 'bandwidths'
  end

  root 'servers#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bandwidth.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: bandwidths
#
#  id             :bigint           not null, primary key
#  interface_name :text             not null
#  value          :float            not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  server_id      :bigint
#  value_id       :integer          not null
#
# Indexes
#
#  index_bandwidths_on_interface_name  (interface_name)
#  index_bandwidths_on_server_id       (server_id)
#
class Bandwidth < ApplicationRecord
  belongs_to :server
  validates :interface_name, uniqueness: { scope: :server_id } # rubocop:todo Rails/UniqueValidationWithoutIndex
end

app/models/server.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: servers
#
#  id         :integer          not null, primary key
#  name       :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Server < ApplicationRecord
  has_many :bandwidths, dependent: :destroy
end

app/controllers/api/v1/api_controller.rb
# frozen_string_literal: true

class Api::V1::ApiController < ApplicationController
end

app/controllers/api/v1/servers/bandwidths_controller.rb
# frozen_string_literal: true

class Api::V1::Servers::BandwidthsController < Api::V1::ApiController
  def index
    pagy, bandwidths = pagy(Bandwidth.where(['server_id = :s', { s: params['server_id'] }]), items: params[:per_page])

    data = ActiveModelSerializers::SerializableResource.new(bandwidths, each_serializer: BandwidthSerializer)

    render json: { data: data, pagination: pagy_metadata(pagy) }
  end
end

app/controllers/api/v1/servers_controller.rb
# frozen_string_literal: true

class Api::V1::ServersController < Api::V1::ApiController
  def index
    pagy, servers = pagy(Server.all, items: params[:per_page])

    data = ActiveModelSerializers::SerializableResource.new(servers, each_serializer: ServerSerializer)

    render json: { data: data, pagination: pagy_metadata(pagy) }
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pagy::Backend

  rescue_from ActiveRecord::RecordNotFound, with: :not_found_error
  rescue_from Pagy::OverflowError, with: :not_found_error

  def destroy
    # TODO

    head :ok
  end

  def not_found_error
    # TODO

    head :ok
  end
end

app/controllers/bandwidths_controller.rb
# frozen_string_literal: true

class BandwidthsController < ApplicationController
  def index
    @pagy, @bandwidths = pagy(Bandwidth.where(['server_id = :s', { s: params['server_id'] }]), items: params[:per_page])
  end
end

app/controllers/servers_controller.rb
# frozen_string_literal: true

class ServersController < ApplicationController
  def index
    @pagy, @servers = pagy(Server.all, items: params[:per_page])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Backend
  include Pagy::Frontend
end

app/views/bandwidths/_bandwidth.html.haml
%tr
  %td #{bandwidth.value_id}. #{bandwidth.interface_name}
  %td= bandwidth.value

app/views/bandwidths/index.html.haml
%table
  %thead
    %tr
      %td.breadcrumbs{ colspan: 3 }
        = link_to I18n.t('bandwidths.breadcrumbs.servers'), '/'
        \/
        = params[:server_id]
        \/
        = I18n.t('bandwidths.breadcrumbs.interfaces')
    %tr
      %th{ colspan: 3 }
        %h1
          = link_to '<', '/', class: 'no-underline'
          = I18n.t('bandwidths.header')
  - if @bandwidths.present?
    %tbody
      %tr
        %th= I18n.t('bandwidths.attributes.interface_name')
        %th= I18n.t('bandwidths.attributes.value')
      = render partial: 'bandwidth', collection: @bandwidths
    - if @pagy.pages > 1
      %tfoot
        %tr
          %th{ colspan: 3 }
            = pagy_nav(@pagy).html_safe # rubocop:todo Rails/OutputSafety
  - else
    %tbody
      %tr
        %td.barely-visible{ colspan: 3 }= I18n.t('bandwidths.missing')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8',
      'http-equiv' => 'Content-Type' }/
    %title Servers
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
  %body
    = yield

app/views/servers/_server.html.haml
%tr
  %td= link_to "#{server.id}. #{server.name}", server_interfaces_path(server.id)

app/views/servers/index.html.haml
%table
  %thead
    %tr
      %td.breadcrumbs= I18n.t('servers.breadcrumbs.servers')
    %tr
      %th
        %h1= I18n.t('servers.header')
  - if @servers.present?
    %tbody
      = render partial: 'server', collection: @servers
    - if @pagy.pages > 1
      %tfoot
        %tr
          %th= pagy_nav(@pagy).html_safe # rubocop:todo Rails/OutputSafety
  - else
    %tbody
      %tr
        %td.barely-visible= I18n.t('servers.missing')